spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/ats_system
    username: postgres
    password: CHANGE_ME

  jpa:
    show-sql: true

logging:
  level:
    com.yasarbilgi.ats: DEBUG
    org.hibernate.SQL: DEBUG

security:
  platform-admin:
    full-name: ${PLATFORM_ADMIN_FULL_NAME:Super Admin}
    email: ${PLATFORM_ADMIN_EMAIL:}
    password: ${PLATFORM_ADMIN_PASSWORD:}
  jwt:
    secret: CHANGE_ME_WITH_AT_LEAST_32_CHARACTERS
