spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/ats_system
    username: postgres
    password: CHANGE_ME

  jpa:
    show-sql: true

logging:
  level:
    com.yasarbilgi.ats: DEBUG
    org.hibernate.SQL: DEBUG

security:
  jwt:
    secret: CHANGE_ME_WITH_AT_LEAST_32_CHARACTERS
